package com.example.financeapp.data.local.database.entities

import androidx.room.Entity
import androidx.room.PrimaryKey
import androidx.room.TypeConverters
import com.example.financeapp.data.models.Transaction

@Entity(tableName = "transactions")
@TypeConverters(Converters::class)
data class TransactionEntity(
    @PrimaryKey
    val id: String = "",
    val date: String = "",
    val dayOfWeek: String = "",
    val category: String = "",
    val categoryId: String = "",
    val amount: Double = 0.0,
    val isIncome: Boolean = false,
    val group: String = "",
    val wallet: String = "",
    val description: String = "",
    val categoryIcon: String? = null,
    val categoryColor: String? = null,
    val createdAt: Long = System.currentTimeMillis(),
    val isAutoGenerated: Boolean = false,
    val recurringSourceId: String = "",
    val userId: String = "", // Thêm userId để phân biệt user
    val isSynced: Boolean = false // Để đồng bộ với Firestore
) {
    fun toTransaction(): Transaction {
        return Transaction(
            id = id,
            date = date,
            dayOfWeek = dayOfWeek,
            category = category,
            categoryId = categoryId,
            amount = amount,
            isIncome = isIncome,
            group = group,
            wallet = wallet,
            description = description,
            categoryIcon = categoryIcon,
            categoryColor = categoryColor,
            createdAt = createdAt,
            isAutoGenerated = isAutoGenerated,
            recurringSourceId = recurringSourceId
        )
    }

    companion object {
        fun fromTransaction(transaction: Transaction, userId: String): TransactionEntity {
            return TransactionEntity(
                id = transaction.id,
                date = transaction.date,
                dayOfWeek = transaction.dayOfWeek,
                category = transaction.category,
                categoryId = transaction.categoryId,
                amount = transaction.amount,
                isIncome = transaction.isIncome,
                group = transaction.group,
                wallet = transaction.wallet,
                description = transaction.description,
                categoryIcon = transaction.categoryIcon,
                categoryColor = transaction.categoryColor,
                createdAt = transaction.createdAt,
                isAutoGenerated = transaction.isAutoGenerated,
                recurringSourceId = transaction.recurringSourceId,
                userId = userId,
                isSynced = false
            )
        }
    }
}