// utils/invoice/InvoiceParser.kt
package com.example.financeapp.utils.invoice

import com.example.financeapp.data.models.Transaction
import java.text.SimpleDateFormat
import java.util.*

class InvoiceParser {

    data class ParseResult(
        val transaction: Transaction,
        val confidence: Float,
        val invoiceNumber: String? = null,
        val taxCode: String? = null
    )

    // Vietnamese invoice patterns
    private val merchantPatterns = listOf(
        Regex("(?i)(?:cửa hàng|shop|store|mua tại|tên đơn vị)[:：\\s]*([^\\n]+)"),
        Regex("(?i)(?:CỬA HÀNG|ĐƠN VỊ)[:：\\s]*([^\\n]+)"),
        Regex("(?i)^\\s*([A-ZÀ-Ỹ][A-ZÀ-Ỹ\\s]{2,})\\s*$")
    )

    private val datePatterns = listOf(
        Regex("(?i)(?:ngày|date)[:：\\s]*(\\d{1,2}[/-]\\d{1,2}[/-]\\d{4})"),
        Regex("(\\d{1,2}[/-]\\d{1,2}[/-]\\d{4}\\s+\\d{1,2}:\\d{2})"),
        Regex("(\\d{1,2}[/-]\\d{1,2}[/-]\\d{2})")
    )

    private val amountPatterns = listOf(
        Regex("(?i)(?:tổng cộng|thanh toán|total|thành tiền|tong cong)[:：\\s]*([\\d.,]+\\s*[₫đĐvndVND]?)"),
        Regex("([\\d.,]+\\s*[₫đĐ])"),
        Regex("(?i)VNĐ\\s*([\\d.,]+)"),
        Regex("(?i)đ\\s*([\\d.,]+)")
    )

    fun parse(text: String): ParseResult {
        val lines = text.lines()
        var confidence = 0.3f // Base confidence

        // Extract merchant name
        val merchantName = extractMerchantName(lines) ?: "Hóa đơn không xác định"
        if (merchantName != "Hóa đơn không xác định") confidence += 0.3f

        // Extract total amount
        val amount = extractAmount(lines) ?: 0.0
        val amountFound = amount > 0
        if (amountFound) confidence += 0.25f

        // Extract date
        val date = extractDate(lines) ?: getCurrentDate()

        // Get day of week
        val calendar = Calendar.getInstance()
        val days = listOf("CN", "T2", "T3", "T4", "T5", "T6", "T7")
        val dayOfWeek = days[calendar.get(Calendar.DAY_OF_WEEK) - 1]

        // Auto-categorize based on merchant name
        val category = autoCategorize(merchantName)

        // Create transaction
        val transaction = Transaction(
            id = UUID.randomUUID().toString(),
            title = merchantName,
            amount = amount,
            date = date,
            dayOfWeek = dayOfWeek,
            category = category.name,
            categoryId = "",
            isIncome = false,
            group = "expense",
            wallet = "Ví chính",
            description = "Hóa đơn quét tự động\n$text",
            categoryIcon = category.icon,
            categoryColor = category.color,
            createdAt = System.currentTimeMillis(),
            isAutoGenerated = false,
            recurringSourceId = ""
        )

        return ParseResult(transaction, confidence.coerceAtMost(0.95f))
    }

    private fun extractMerchantName(lines: List<String>): String? {
        for (pattern in merchantPatterns) {
            for (line in lines) {
                val match = pattern.find(line)
                if (match != null && match.groupValues.size > 1) {
                    return match.groupValues[1].trim()
                }
            }
        }
        return null
    }

    private fun extractAmount(lines: List<String>): Double? {
        for (pattern in amountPatterns) {
            for (line in lines) {
                val match = pattern.find(line)
                if (match != null) {
                    val amountStr = match.groupValues[1]
                        .replace(Regex("[₫đĐVNDvnd,]"), "")
                        .replace(".", "")
                        .trim()

                    return try {
                        amountStr.toDouble()
                    } catch (e: Exception) {
                        null
                    }
                }
            }
        }
        return null
    }

    private fun extractDate(lines: List<String>): String? {
        for (pattern in datePatterns) {
            for (line in lines) {
                val match = pattern.find(line)
                if (match != null) {
                    var dateStr = match.groupValues[1].trim()

                    // Try to parse date
                    return try {
                        // Normalize date format
                        dateStr = dateStr.replace("-", "/")

                        // If date has 2-digit year, convert to 4-digit
                        if (dateStr.matches(Regex("\\d{1,2}/\\d{1,2}/\\d{2}"))) {
                            val parts = dateStr.split("/")
                            val year = if (parts[2].toInt() < 30) "20${parts[2]}" else "19${parts[2]}"
                            "${parts[0]}/${parts[1]}/$year"
                        } else {
                            dateStr
                        }
                    } catch (e: Exception) {
                        null
                    }
                }
            }
        }
        return null
    }

    private fun getCurrentDate(): String {
        val dateFormat = SimpleDateFormat("dd/MM/yyyy", Locale.getDefault())
        return dateFormat.format(Date())
    }

    private fun autoCategorize(merchantName: String): Category {
        val lowerName = merchantName.lowercase(Locale.getDefault())

        return when {
            // Food & Drink
            lowerName.contains("coffee") || lowerName.contains("highlands") ||
                    lowerName.contains("trung nguyên") || lowerName.contains("phúc long") ||
                    lowerName.contains("the coffee") || lowerName.contains("starbucks") ||
                    lowerName.contains("quán ăn") || lowerName.contains("nhà hàng") ||
                    lowerName.contains("tiệm bánh") || lowerName.contains("quán nước") ||
                    lowerName.contains("kfc") || lowerName.contains("lotteria") ||
                    lowerName.contains("pizza") || lowerName.contains("burger") ->
                Category("food", "Ăn uống", "🍽️", "#4CAF50")

            // Convenience stores
            lowerName.contains("circle k") || lowerName.contains("ministop") ||
                    lowerName.contains("family mart") || lowerName.contains("b's mart") ||
                    lowerName.contains("tiện lợi") || lowerName.contains("tiệm tạp hóa") ||
                    lowerName.contains("cửa hàng tiện lợi") ->
                Category("convenience", "Tiện ích", "🏪", "#2196F3")

            // Supermarkets
            lowerName.contains("vinmart") || lowerName.contains("coopmart") ||
                    lowerName.contains("big c") || lowerName.contains("saigon coop") ||
                    lowerName.contains("aeon") || lowerName.contains("siêu thị") ||
                    lowerName.contains("bách hóa xanh") ->
                Category("groceries", "Siêu thị", "🛒", "#FF9800")

            // Gas stations
            lowerName.contains("petrolimex") || lowerName.contains("shell") ||
                    lowerName.contains("total") || lowerName.contains("trạm xăng") ->
                Category("transport", "Xăng xe", "⛽", "#9C27B0")

            // Pharmacies
            lowerName.contains("pharmacity") || lowerName.contains("long châu") ||
                    lowerName.contains("nhà thuốc") || lowerName.contains("dược") ->
                Category("health", "Sức khỏe", "💊", "#F44336")

            // Electronics
            lowerName.contains("điện máy") || lowerName.contains("nguyễn kim") ||
                    lowerName.contains("thế giới di động") || lowerName.contains("fpt shop") ||
                    lowerName.contains("cellphones") ->
                Category("electronics", "Điện tử", "📱", "#607D8B")

            // Default
            else -> Category("shopping", "Mua sắm", "🛍️", "#9C27B0")
        }
    }

    data class Category(
        val id: String,
        val name: String,
        val icon: String,
        val color: String
    )
}