package com.example.financeapp

import com.example.financeapp.data.models.Transaction
import com.google.firebase.firestore.FirebaseFirestore
import com.google.firebase.firestore.ktx.firestore
import com.google.firebase.ktx.Firebase
import kotlinx.coroutines.tasks.await

class FirestoreService {
    private val db: FirebaseFirestore = Firebase.firestore

    suspend fun saveTransaction(transaction: Transaction) {
        try {
            val transactionMap = mapOf(
                "id" to transaction.id,
                "date" to transaction.date,
                "dayOfWeek" to transaction.dayOfWeek,
                "category" to transaction.category,
                "categoryId" to transaction.categoryId,
                "amount" to transaction.amount,
                "isIncome" to transaction.isIncome,
                "group" to transaction.group,
                "wallet" to transaction.wallet,
                "description" to (transaction.description ?: ""),
                "title" to (transaction.title.ifBlank { transaction.category }),
                "categoryIcon" to (transaction.categoryIcon ?: ""),
                "categoryColor" to (transaction.categoryColor ?: ""),
                "createdAt" to (transaction.createdAt),
                "isAutoGenerated" to transaction.isAutoGenerated,
                "recurringSourceId" to transaction.recurringSourceId
            )

            db.collection("transactions")
                .document(transaction.id)
                .set(transactionMap)
                .await()
        } catch (e: Exception) {
            throw e
        }
    }

    suspend fun getTransactions(): List<Transaction> {
        return try {
            val snapshot = db.collection("transactions")
                .get()
                .await()

            snapshot.documents.map { doc ->
                val data = doc.data ?: emptyMap()
                Transaction(
                    id = data["id"] as? String ?: doc.id,
                    date = data["date"] as? String ?: "",
                    dayOfWeek = data["dayOfWeek"] as? String ?: "",
                    category = data["category"] as? String ?: "",
                    categoryId = data["categoryId"] as? String ?: "",
                    amount = (data["amount"] as? Double) ?: 0.0,
                    isIncome = data["isIncome"] as? Boolean ?: false,
                    group = data["group"] as? String ?: "",
                    wallet = data["wallet"] as? String ?: "",
                    description = data["description"] as? String ?: "",
                    title = data["title"] as? String ?: (data["category"] as? String ?: ""),
                    categoryIcon = (data["categoryIcon"] as? String)?.takeIf { it.isNotBlank() },
                    categoryColor = (data["categoryColor"] as? String)?.takeIf { it.isNotBlank() },
                    createdAt = (data["createdAt"] as? Long) ?: System.currentTimeMillis(),
                    isAutoGenerated = data["isAutoGenerated"] as? Boolean ?: false,
                    recurringSourceId = data["recurringSourceId"] as? String ?: ""
                )
            }
        } catch (e: Exception) {
            emptyList()
        }
    }

    suspend fun deleteTransaction(transactionId: String) {
        try {
            db.collection("transactions")
                .document(transactionId)
                .delete()
                .await()
        } catch (e: Exception) {
            throw e
        }
    }
}