package com.example.financeapp.viewmodel.settings

import androidx.lifecycle.ViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow

data class Language(val code: String, val name: String)

class LanguageViewModel : ViewModel() {
    private val _currentLanguage = MutableStateFlow(Language("vi", "Tiếng Việt"))
    val currentLanguage: StateFlow<Language> = _currentLanguage.asStateFlow()

    private val _languageCode = MutableStateFlow("vi")
    val languageCode: StateFlow<String> = _languageCode.asStateFlow()

    // Translations dictionary
    private val translations = mapOf(
        "vi" to mapOf(
            "budgets" to "ngân sách",
            "view_all_budgets" to "Xem tất cả ngân sách",
            "add_new_budget" to "Thêm ngân sách mới",
            "no_budget_setup" to "Chưa có ngân sách nào",
            "setup_budget_description" to "Thiết lập ngân sách để quản lý chi tiêu hiệu quả hơn",
            "this_month" to "Tháng này",
            // Basic app and navigation
            "language_settings" to "Cài đặt ngôn ngữ",
            "choose_language" to "Chọn ngôn ngữ",
            "current_language" to "Ngôn ngữ hiện tại",
            "language_saved" to "Đã lưu ngôn ngữ",
            "language_reset" to "Đã khôi phục ngôn ngữ",
            "save" to "Lưu",
            "reset" to "Khôi phục",
            "language" to "Ngôn ngữ",
            "app_title" to "Quản lý chi tiêu",
            "cancel" to "Hủy",
            "back" to "Quay lại",
            "next" to "Tiếp theo",
            "loading" to "Đang tải",
            "error" to "Lỗi",
            "success" to "Thành công",
            "warning" to "Cảnh báo",
            "info" to "Thông tin",
            "add" to "Thêm",
            "edit" to "Sửa",
            "delete" to "Xóa",
            "confirm" to "Xác nhận",
            "extensions" to "Tiện ích mở rộng",
            "extra_tools_like_ai_calendar_scan" to "Các công cụ bổ sung như Danh Mục, Ngân Sách, Chi Tiêu Định Kỳ",

            // SettingsScreen specific
            "settings" to "Cài đặt",
            "account" to "Tài khoản",
            "personal_info" to "Thông tin cá nhân",
            "manage_account_info" to "Quản lý thông tin tài khoản",
            "application_settings" to "Cài đặt ứng dụng",
            "notifications" to "Thông báo",
            "notifications_on" to "Đã bật",
            "notifications_off" to "Đã tắt",
            "ai_calendar_scan" to "AI, Lịch, Quét hóa đơn",
            "support" to "Hỗ trợ",
            "help" to "Trợ giúp",
            "frequently_asked_questions" to "Câu hỏi thường gặp",
            "about_app" to "Về ứng dụng",
            "version" to "Phiên bản",
            "logout" to "Đăng xuất",
            "logout_account" to "Đăng xuất khỏi tài khoản",
            "actions" to "Hành động",
            "information" to "Thông tin",
            "language_change_info" to "Thay đổi ngôn ngữ sẽ áp dụng cho toàn bộ ứng dụng",
            "close" to "Đóng",
            "confirm_logout" to "Bạn có chắc muốn đăng xuất khỏi tài khoản?",
            "finance_app" to "Finance App",
            "personal_finance_app" to "Ứng dụng quản lý tài chính cá nhân",
            "release_date" to "Ngày phát hành",
            "footer_copyright" to "WendyAI App © 2025",



            // ========== MỚI: THÊM TỪ HOME SCREEN ==========
            // HomeScreen specific
            // HomeScreen specific
            "home" to "Trang chủ",
            "greeting" to "Xin chào",
            "user" to "Người dùng",
            "income" to "Thu nhập",
            "expense" to "Chi tiêu",
            "this_month" to "Trong tháng",
            "recent_transactions" to "Giao dịch gần đây",
            "view_all" to "Xem tất cả",
            "no_recent_transactions" to "Bạn chưa có giao dịch gần đây",
            "create_transaction" to "Tạo giao dịch",
            "spending_chart_title" to "Chi tiêu 7 ngày qua",
            "monthly_spent" to "Tháng này",
            "budget_title" to "Ngân sách tháng",
            "manage_budget" to "Quản lý ngân sách",
            "tracking_budget" to "Đang theo dõi",
            "setup_budget" to "Thiết lập ngân sách",
            "setup_budget_description" to "Thiết lập ngân sách để kiểm soát chi tiêu",
            "view_details" to "Xem chi tiết",
            "setup_budget_button" to "Thiết lập ngân sách",
            "spent" to "Đã chi",
            "budget" to "Ngân sách",
            "remaining" to "Còn lại",
            "over_budget" to "Vượt ngân sách",
            "spending_7_days" to "Chi tiêu 7 ngày qua",
            "no_chart_data" to "Chưa có dữ liệu biểu đồ",
            "income_card_title" to "Thu nhập",
            "expense_card_title" to "Chi tiêu",
            "transaction" to "Giao dịch",
            "today" to "Hôm nay",
            "yesterday" to "Hôm qua",
            "amount" to "Số tiền",
            "description" to "Mô tả",
            "calendar" to "Lịch",
            "greeting" to "Xin chào",
            "user" to "Người dùng",
            "monthly_spending_title" to "Số tiền bạn đã chi trong tháng",
            "view_details" to "Xem chi tiết",
            "spent_this_month" to "Số tiền đã chi tiêu trong tháng này",
            "classification_by_type" to "Chi theo phân loại",
            "recent_transactions" to "Giao dịch gần đây",
            "view_all" to "Xem tất cả",
            "income" to "Thu",
            "expense" to "Chi",
            "no_recent_transactions" to "Bạn chưa có giao dịch gần đây",
            "create_transaction" to "Tạo giao dịch",
            "overview" to "Tổng quan",
            "this_month" to "Tháng này",
            "spending_limit" to "Hạn mức chi tiêu",
            "create_or_select_fund_for_limit" to "Tạo hoặc lựa chọn quỹ tiết kiệm",
            "limit_description" to "để chúng tôi tính toán hạn mức chi tiêu",
            "select_or_create_fund" to "Lựa chọn / Tạo quỹ tiết kiệm",
            "no_chart_data" to "Chưa có dữ liệu biểu đồ",
            "spending_by_category" to "Chi theo phân loại",
            "daily_spending" to "Chi tiêu hằng ngày",
            "savings_fund" to "Tiền sâu TH",
            "needs" to "Cần thiết",
            "training" to "Đào tạo",
            "entertainment" to "Hoan hỉ",
            "savings" to "Tiết kiệm",
            "self_care" to "Tự thẩm",
            "free_spending" to "Tự do",
            "limit" to "Hạn mức",
            "spent" to "Đã tiêu",
            "see_more" to "Xem thêm",
            "monthly_spending_total" to "Số tiền đã chi tiêu trong tháng",
            "transactions" to "Giao dịch",
            "profile" to "Cá nhân",
            // =============================================

            // Main navigation
            "home" to "Trang chủ",
            "statistics" to "Thống kê",
            "transactions" to "Giao dịch",
            "categories" to "Danh mục",
            "reports" to "Báo cáo",
            "account" to "Tài khoản",

            // HomeScreen (phần cũ - giữ lại cho tương thích)
            "total_balance" to "Tổng số dư",
            "need_attention" to "Cần chú ý",
            "stable" to "Ổn định",
            "status" to "Tình trạng",
            "financial_trend" to "Tình hình thu chi",
            "month" to "Tháng",
            "spending" to "Chi tiêu",
            "total" to "Tổng",
            "line_chart" to "Biểu đồ đường",
            "column_chart" to "Biểu đồ cột",
            "pie_chart" to "Biểu đồ tròn",
            "no_data" to "Chưa có dữ liệu để hiển thị",
            "no_spending_data" to "Chưa có dữ liệu chi tiêu để hiển thị",
            "no_transactions" to "Chưa có giao dịch nào",
            "reset_password" to "Thay đổi mật khẩu",
            "time_range" to "Khoảng thời gian",
            "data_type" to "Loại dữ liệu",

            // TransactionScreen
            "transaction_book" to "Sổ giao dịch",
            "transactions_count" to "giao dịch",
            "financial_overview" to "Tổng quan tài chính",
            "monthly_income" to "Thu tháng",
            "monthly_expense" to "Chi tháng",
            "transaction_count" to "Số giao dịch",
            "transaction_history" to "Lịch sử giao dịch",
            "no_note" to "Không có ghi chú",
            "delete_transaction" to "Xóa giao dịch",
            "delete_confirmation" to "Bạn có chắc chắn muốn xóa giao dịch",
            "confirm_delete" to "Xác nhận xóa",
            "no_transactions_description" to "Bắt đầu bằng cách thêm giao dịch đầu tiên của bạn",

            // AddTransactionScreen
            "record_transaction" to "Ghi lại giao dịch",
            "manual_input" to "Nhập thủ công",
            "image_input" to "Nhập từ ảnh",
            "select_category" to "Chọn danh mục",
            "transaction_date" to "Ngày giao dịch",
            "today" to "Hôm nay",
            "repeat_frequency" to "Tần suất lặp lại",
            "no_repeat" to "Không lặp lại",
            "daily" to "Hàng ngày",
            "weekly" to "Hàng tuần",
            "monthly" to "Hàng tháng",
            "note" to "Ghi chú",
            "enter_transaction_description" to "Nhập mô tả giao dịch",
            "update_transaction" to "Cập nhật giao dịch",
            "add_income_transaction" to "Thêm thu nhập",
            "add_expense_transaction" to "Thêm chi tiêu",
            "delete_transaction_dialog" to "Xóa giao dịch",
            "delete_transaction_description" to "Bạn có chắc chắn muốn xóa giao dịch này?",
            "delete_action" to "Xóa",

            // Categories
            "food_drink" to "Ăn uống",
            "shopping" to "Mua sắm",
            "family" to "Gia đình",
            "other" to "Khác",

            // Calendar Screen
            "calendar" to "Lịch",
            "difference" to "Chênh lệch",
            "transaction_list" to "Danh sách giao dịch",
            "select_other_day" to "Chọn ngày khác để xem giao dịch",
            "previous_month" to "Tháng trước",
            "next_month" to "Tháng sau",

            // Days of week (short)
            "monday_short" to "T2",
            "tuesday_short" to "T3",
            "wednesday_short" to "T4",
            "thursday_short" to "T5",
            "friday_short" to "T6",
            "saturday_short" to "T7",
            "sunday_short" to "CN",

            // Days of week (full)
            "monday" to "Thứ Hai",
            "tuesday" to "Thứ Ba",
            "wednesday" to "Thứ Tư",
            "thursday" to "Thứ Năm",
            "friday" to "Thứ Sáu",
            "saturday" to "Thứ Bảy",
            "sunday" to "Chủ Nhật",

            // Months
            "january" to "Tháng 1",
            "february" to "Tháng 2",
            "march" to "Tháng 3",
            "april" to "Tháng 4",
            "may" to "Tháng 5",
            "june" to "Tháng 6",
            "july" to "Tháng 7",
            "august" to "Tháng 8",
            "september" to "Tháng 9",
            "october" to "Tháng 10",
            "november" to "Tháng 11",
            "december" to "Tháng 12",
            "yearly_comparison" to "Biến động",

            // Help & Support
            "help_support" to "Trợ giúp & Hỗ trợ",
            "faq" to "Câu hỏi thường gặp",
            "faq_add_transaction" to "Làm sao để thêm giao dịch?",
            "faq_add_transaction_answer" to "Vào Trang chủ → bấm nút \"+\" màu xanh ở góc phải dưới màn hình",
            "faq_view_statistics" to "Làm sao để xem thống kê?",
            "faq_view_statistics_answer" to "Vào mục Thống kê → chọn khoảng thời gian và loại dữ liệu muốn xem",
            "faq_logout" to "Làm sao để đăng xuất?",
            "faq_logout_answer" to "Vào Cài đặt → cuộn xuống → chọn \"Đăng xuất\"",
            "faq_change_theme" to "Làm sao để thay đổi theme?",
            "faq_change_theme_answer" to "Vào Cài đặt → bật/tắt \"Chế độ giao diện\"",
            "contact_support" to "Liên hệ hỗ trợ",
            "contact_description" to "Nếu bạn cần hỗ trợ thêm hoặc gặp sự cố kỹ thuật, vui lòng liên hệ:",
            "email" to "Email",
            "website" to "Website",
            "working_hours" to "Giờ làm việc",
            "response_time" to "Phản hồi trong 24h",
            "detailed_guide" to "Hướng dẫn chi tiết",
            "weekdays" to "Thứ 2 - Thứ 6",
            "working_time" to "8:00 - 17:00",
            "usage_tips" to "Mẹo sử dụng",
            "tip_categories" to "Sử dụng danh mục để phân loại chi tiêu rõ ràng",
            "tip_savings" to "Đặt mục tiêu tiết kiệm để theo dõi tiến độ",
            "tip_statistics" to "Xem thống kê hàng tháng để điều chỉnh chi tiêu",
            "tip_reminders" to "Sử dụng tính năng nhắc nhở cho hóa đơn định kỳ",

            // Common transaction fields
            "amount" to "Số tiền",
            "description" to "Mô tả",
            "date" to "Ngày",
            "category" to "Danh mục",
            "add_expense" to "Thêm chi tiêu",
            "expense_list" to "Danh sách chi tiêu",
            "add_transaction" to "Thêm giao dịch",
            "total_income" to "Tổng thu",
            "total_expense" to "Tổng chi",
            "this_week" to "Tuần này",
            "this_year" to "Năm nay",
            "trend_analysis" to "Phân tích xu hướng",
            "category_analysis" to "Phân tích danh mục",

            // Notification settings
            "notification_settings" to "Cài đặt thông báo",
            "customize_notifications" to "Tùy chỉnh cách bạn nhận thông báo",
            "notification_types" to "Loại thông báo",
            "push_notifications" to "Thông báo đẩy (Push)",
            "email_notifications" to "Thông báo qua Email",
            "sms_notifications" to "Thông báo qua SMS",
            "financial_alerts" to "Cảnh báo tài chính",
            "low_balance_alert" to "Cảnh báo số dư thấp",
            "large_transaction_alert" to "Cảnh báo giao dịch lớn",
            "monthly_report" to "Báo cáo tháng",
            "restore" to "Khôi phục",
            "save_settings" to "Lưu cài đặt",
            "settings_restored" to "Đã khôi phục cài đặt",
            "settings_saved" to "Đã lưu cài đặt thông báo",

            // Settings and account
            "manage_personal_info" to "Quản lý thông tin cá nhân",
            "enable_disable_notifications" to "Bật / tắt thông báo",
            "theme_mode" to "Chế độ giao diện",
            "sign_out" to "Đăng xuất",
            "logout_account" to "Thoát khỏi tài khoản của bạn",

            // Đảm bảo các key này đã có
            "statistics" to "Thống kê",
            "time_range" to "Khoảng thời gian",
            "time_range_weekly" to "Theo tuần",
            "time_range_monthly" to "Theo tháng",
            "time_range_yearly" to "Theo năm",
            "data_type" to "Loại dữ liệu",
            "data_type_income" to "Thu nhập",
            "data_type_expense" to "Chi tiêu",
            "data_type_difference" to "Chênh lệch",
            "total" to "Tổng",
            "same_period_as" to "So với cùng kỳ",
            "info" to "Thông tin",
            "total_income" to "Tổng thu nhập",
            "total_expense" to "Tổng chi tiêu",
            "difference" to "Chênh lệch",
            "no_data" to "Không có dữ liệu",
            "no_transactions_time_period" to "Bạn không có giao dịch nào trong khoảng thời gian này",
            "compare" to "So sánh",
            "with" to "với",
            "this_week" to "Tuần này",
            "this_month" to "Tháng này",
            "this_year" to "Năm nay",
            "last_week" to "tuần trước",
            "last_month" to "tháng trước",
            "last_year" to "năm trước",
            "current_week" to "Tuần hiện tại",
            "current_month" to "Tháng hiện tại",
            "current_year" to "Năm hiện tại",
            "previous_week" to "Tuần trước",
            "previous_month" to "Tháng trước",
            "previous_year" to "Năm trước",
            "category_analysis" to "Phân tích danh mục",
            "category" to "Danh mục",
            "amount" to "Số tiền",
            "unknown_category" to "Không xác định",

            // Add/Edit Recurring Expense Screen
            "edit_recurring_expense" to "Chỉnh sửa chi tiêu định kỳ",
            "add_recurring_expense_button" to "Thêm chi tiêu",
            "expense_info" to "Thông tin chi tiêu",
            "title" to "Tiêu đề",
            "title_placeholder" to "Ví dụ: Tiền nhà, Internet...",
            "amount" to "Số tiền",
            "category" to "Danh mục",
            "no_categories" to "Chưa có danh mục nào",
            "frequency" to "Tần suất",
            "wallet" to "Ví",
            "main_wallet" to "Ví chính",
            "main_wallet_placeholder" to "Ví chính",
            "start_date" to "Ngày bắt đầu",
            "end_date_optional" to "Ngày kết thúc (tùy chọn)",
            "select_date" to "Chọn ngày",
            "no_end_date" to "Không có ngày kết thúc",
            "notes" to "Ghi chú",
            // Main Screen & Navigation
            "recurring_expenses" to "Chi tiêu định kỳ",
            "add_recurring_expense" to "Thêm chi tiêu định kỳ",
            "back" to "Quay lại",

// Stats Card
            "total_expenses" to "Tổng chi tiêu",
            "active_lower" to "đang hoạt động",
            "monthly_expenses" to "Chi hàng tháng",

// Expense Card
            "menu" to "Menu",
            "edit" to "Chỉnh sửa",
            "pause" to "Tạm dừng",
            "activate" to "Kích hoạt",
            "delete" to "Xóa",
            "next" to "Tiếp theo",
            "generated" to "Đã tạo",
            "times" to "lần",

// Empty State
            "no_recurring_expenses" to "Không có chi tiêu định kỳ",
            "no_recurring_expenses_yet" to "Chưa có chi tiêu định kỳ nào",
            "add_recurring_expense_to_manage" to "Thêm chi tiêu định kỳ để quản lý chi tiêu tự động",

// Delete Dialog
            "delete_recurring_expense" to "Xóa chi tiêu định kỳ",
            "confirm_delete_recurring_expense" to "Bạn có chắc muốn xóa",
            "warning" to "Cảnh báo",
            "cancel" to "Hủy",
            "action_cannot_be_undone" to "Hành động này không thể hoàn tác.",

// Status Dialog
            "confirm" to "Bạn có chắc muốn",

// Frequency Types
            "daily" to "Hàng ngày",
            "weekly" to "Hàng tuần",
            "monthly" to "Hàng tháng",
            "quarterly" to "Hàng quý",
            "annually" to "Hàng năm",
// Tần suất (đã có từ trước)
            "daily" to "Hàng ngày",
            "weekly" to "Hàng tuần",
            "monthly" to "Hàng tháng",
            "quarterly" to "Hàng quý",
            "yearly" to "Hàng năm",

// Các key tái sử dụng từ các màn hình khác
            "back" to "Quay lại",
            "currency_vnd" to "VND",
            "add_note_placeholder" to "Thêm ghi chú...",
            "update" to "Cập nhật",

            // Thêm vào map "vi" (Tiếng Việt):
            "compare" to "So sánh",
            "with" to "với",
            "current_week" to "Tuần này",
            "previous_week" to "Tuần trước",
            "current_month" to "Tháng này",
            "previous_month" to "Tháng trước",
            "current_year" to "Năm nay",
            "previous_year" to "Năm trước",

            "balance" to "Số dư",
            "current_balance" to "Số dư hiện tại",
            "total_balance" to "Tổng số dư",
            "balance_overview" to "Tổng quan số dư",
            "available_balance" to "Số dư khả dụng",
            "remaining_balance" to "Số dư còn lại",

            // Account info
            "account_info" to "Thông tin tài khoản",
            "update_personal_info" to "Cập nhật thông tin cá nhân",
            "full_name" to "Họ và tên",
            "phone_number" to "Số điện thoại",
            "read_only" to "Chỉ đọc",
            "update_success" to "Cập nhật thành công",
            "saving" to "Đang lưu...",
            "save_changes" to "Lưu thay đổi",
            "system_info" to "Thông tin hệ thống",
            "user_id" to "ID người dùng",
            "not_available" to "Không có sẵn",
            "provider" to "Nhà cung cấp",
            "email_verification" to "Xác thực email",
            "verified" to "Đã xác thực",
            "not_verified" to "Chưa xác thực",
            "created_at" to "Tạo lúc",
            "last_login" to "Đăng nhập lần cuối",
            "unknown" to "Không xác định",
            "email_password" to "Email/Mật khẩu",
            "google" to "Google",
            "facebook" to "Facebook",

            // Category Management
            "create_category" to "Tạo danh mục",
            "click_to_change_icon" to "Chạm để đổi biểu tượng",
            "category_name" to "Tên danh mục",
            "category_name_example" to "Ví dụ: Ăn uống, Mua sắm...",
            "parent_category" to "Danh mục cha",
            "select_parent_category" to "Chọn danh mục cha",
            "select_category" to "Chọn danh mục",
            "icon" to "Biểu tượng",
            "ready_to_create_category" to "Sẵn sàng tạo danh mục",
            "select_icon" to "Chọn biểu tượng",
            "select_group_for_new_category" to "Chọn nhóm cho danh mục mới",
            "search_categories" to "Tìm kiếm danh mục...",
            "found" to "Tìm thấy",
            "categories" to "danh mục",
            "no_categories_found" to "Không tìm thấy danh mục",
            "try_different_keywords" to "Thử từ khóa khác",
            "main_category" to "Danh mục chính",
            "sub_category" to "Danh mục con",
            "category_management" to "Quản lý danh mục",
            "add_new_category" to "Thêm danh mục mới",
            "has" to "Đã có",
            "add_sub_category" to "Thêm danh mục con",
            "no_sub_categories" to "Chưa có danh mục con",
            "sub_categories" to "danh mục con",

            // Budget Screen
            "budgets" to "Ngân sách",
            "add_budget" to "Thêm ngân sách",
            "total_budget" to "Tổng ngân sách",
            "active" to "đang hoạt động",
            "spent" to "Đã chi",
            "unknown_category" to "Không xác định",
            "menu" to "Menu",
            "edit" to "Chỉnh sửa",
            "pause" to "Tạm dừng",
            "activate" to "Kích hoạt",
            "delete" to "Xóa",
            "remaining" to "Còn lại",
            "no_budgets" to "Không có ngân sách",
            "no_budgets_yet" to "Chưa có ngân sách nào",
            "add_budget_to_manage_spending" to "Thêm ngân sách để quản lý chi tiêu",
            "this_budget" to "ngân sách này",
            "warning" to "Cảnh báo",
            "delete_budget" to "Xóa ngân sách",
            "confirm_delete_budget" to "Bạn có chắc muốn xóa",
            "action_cannot_be_undone" to "Hành động này không thể hoàn tác",
            "confirm" to "Bạn có chắc muốn",
            // Các key mới cho RecurringExpenseScreen
            "recurring_expenses" to "Chi tiêu định kỳ",
            "add_recurring_expense" to "Thêm chi tiêu định kỳ",
            "total_expenses" to "Tổng chi tiêu",
            "active_lower" to "đang hoạt động",
            "monthly_expenses" to "Chi hàng tháng",
            "next" to "Tiếp theo",
            "generated" to "Đã tạo",
            "times" to "lần",
            "no_recurring_expenses" to "Không có chi tiêu định kỳ",
            "no_recurring_expenses_yet" to "Chưa có chi tiêu định kỳ nào",
            "add_recurring_expense_to_manage" to "Thêm chi tiêu định kỳ để quản lý chi tiêu tự động",
            "delete_recurring_expense" to "Xóa chi tiêu định kỳ",
            "confirm_delete_recurring_expense" to "Bạn có chắc muốn xóa",

// Các key tần suất (frequency) theo code hiện tại của bạn
            "daily" to "Hàng ngày",
            "weekly" to "Hàng tuần",
            "biweekly" to "Hai tuần một lần",
            "monthly" to "Hàng tháng",
            "quarterly" to "Hàng quý",
            "yearly" to "Hàng năm", // Dùng yearly thay vì annually để phù hợp với RecurringFrequency.YEARLY

// Các key tái sử dụng từ BudgetScreen (cần check xem đã có chưa)
            "back" to "Quay lại",
            "menu" to "Menu",
            "edit" to "Chỉnh sửa",
            "pause" to "Tạm dừng",
            "activate" to "Kích hoạt",
            "delete" to "Xóa",
            "cancel" to "Hủy",
            "warning" to "Cảnh báo",
            "confirm" to "Bạn có chắc muốn",
            "action_cannot_be_undone" to "Hành động này không thể hoàn tác.",

            "week" to "tuần",
            "month" to "tháng",
            "quarter" to "quý",
            "year" to "năm",
            "currency_vnd" to "VND",
            "add_note_placeholder" to "Thêm ghi chú...",
            "add_budget_button" to "Thêm ngân sách",
            "update" to "Cập nhật",
            // Help Screen - Tiếng Việt
            "help" to "Trợ giúp",
            "faq" to "Câu hỏi thường gặp",
            "contact_support" to "Liên hệ hỗ trợ",
            "usage_tips" to "Mẹo sử dụng",
            "app_info" to "Thông tin ứng dụng",

// FAQ Questions
            "faq_how_to_add_transaction" to "Làm thế nào để thêm giao dịch?",
            "faq_how_to_add_transaction_answer" to "Chuyển đến màn hình Trang chủ, nhấn nút '+' ở dưới cùng, chọn 'Thêm giao dịch', điền thông tin và nhấn 'Lưu'.",
            "faq_how_to_add_wallet" to "Làm thế nào để thêm ví mới?",
            "faq_how_to_add_wallet_answer" to "Vào màn hình Ví, nhấn nút '+' ở góc dưới bên phải, nhập tên ví và số dư ban đầu.",
            "faq_how_to_view_stats" to "Làm thế nào để xem thống kê?",
            "faq_how_to_view_stats_answer" to "Vào màn hình Thống kê từ thanh điều hướng dưới cùng để xem biểu đồ và phân tích chi tiêu.",
            "faq_how_to_logout" to "Làm thế nào để đăng xuất?",
            "faq_how_to_logout_answer" to "Vào màn hình Cài đặt, cuộn xuống và chọn 'Đăng xuất'.",

// Contact Support
            "support_email" to "Email hỗ trợ",
            "response_within_24h" to "Phản hồi trong 24h",
            "website" to "Website",
            "detailed_guides" to "Hướng dẫn chi tiết",
            "working_hours" to "Giờ làm việc",
            "monday_to_friday" to "Thứ 2 - Thứ 6",
            "working_hours_time" to "8:00 - 17:00",

// Usage Tips
            "tip_categorize_expenses" to "Phân loại chi tiêu vào đúng danh mục để thống kê chính xác",
            "tip_set_monthly_budget" to "Thiết lập ngân sách hàng tháng để kiểm soát chi tiêu",
            "tip_use_recurring_expenses" to "Sử dụng tính năng chi tiêu định kỳ cho các khoản chi cố định",
            "tip_view_weekly_stats" to "Xem thống kê hàng tuần để điều chỉnh chi tiêu hợp lý",

// App Info
            "version" to "Phiên bản",
            "release_date" to "Ngày phát hành",
            "release_date_value" to "Tháng 12, 2025",
            "developer" to "Nhà phát triển",
            "developer_value" to "Finance App Team",

// Common
            "question" to "Câu hỏi",
            "expand" to "Mở rộng",
            "collapse" to "Thu gọn",
            // TransactionScreen specific
            "transaction_screen_title" to "Thu - chi",
            "filter_by_time" to "Lọc theo thời gian",
            "today" to "Hôm nay",
            "yesterday" to "Hôm qua",
            "this_week" to "Tuần này",
            "this_month" to "Tháng này",
            "last_month" to "Tháng trước",
            "this_year" to "Năm nay",
            "all" to "Tất cả",
            "apply_filter" to "Áp dụng",
            "filter" to "Lọc",
            "filter_options" to "Lọc theo",
            "close" to "Đóng",
            "spending" to "Tiền chi",
            "income" to "Tiền thu",
            "total" to "Tổng cộng",
            "wallet" to "Ví",
            "unknown_category" to "Không xác định",
            "confirm_delete_transaction" to "Bạn có chắc chắn muốn xóa giao dịch này?",
            "go_back" to "Quay lại",
            "delete" to "Xóa",
            "calendar" to "Lịch",
            "transaction_book" to "Sổ giao dịch",
            "add_transaction" to "Thêm giao dịch",
            "financial_overview" to "Tổng quan tài chính",
            "month" to "Tháng",
            "total_income" to "Tổng thu",
            "total_expense" to "Tổng chi",
            "difference" to "Chênh lệch",
            "monthly_income" to "Thu tháng",
            "monthly_expense" to "Chi tháng",
            "transaction_count" to "Số giao dịch",
            "no_note" to "Không có ghi chú",
            "edit" to "Sửa",
            "no_transactions" to "Chưa có giao dịch nào",
            "no_transactions_description" to "Bắt đầu bằng cách thêm giao dịch đầu tiên của bạn",
            "delete_transaction" to "Xóa giao dịch",
            "delete_confirmation" to "Bạn có chắc chắn muốn xóa giao dịch",
            "confirm_delete" to "Xác nhận xóa",
            // Extensions Screen
            "extensions" to "Tiện ích mở rộng",
            "expense_categories" to "Danh mục chi tiêu",
            "customize_spending_categories" to "Tùy chỉnh danh mục chi tiêu",
            "budgets" to "Ngân sách",
            "set_and_track_monthly_budget" to "Thiết lập và theo dõi ngân sách hàng tháng",
            "recurring_expenses" to "Chi tiêu định kỳ",
            "manage_automatic_monthly_expenses" to "Quản lý chi tiêu tự động hàng tháng",
            "savings_goals" to "Mục tiêu tiết kiệm",
            "track_and_achieve_savings_targets" to "Theo dõi và đạt mục tiêu tiết kiệm",
            "advanced_features" to "Tính năng nâng cao",
            "receipt_scan" to "Quét hóa đơn",
            "scan_receipts_auto_input_expenses" to "Quét hóa đơn tự động nhập chi tiêu",
            "ai_analysis" to "Phân tích AI",
            "ai_powered_spending_analysis" to "Phân tích chi tiêu với trí tuệ nhân tạo",
            "coming_soon" to "Sắp ra mắt",
            "unavailable" to "Không khả dụng",
            // Add Category Screen
            "create_category" to "Tạo danh mục",
            "category_information" to "Thông tin danh mục",
            "click_to_change_icon" to "Nhấn để đổi icon",
            "category_name" to "Tên danh mục",
            "category_name_example" to "Ví dụ: Ăn uống, Mua sắm...",
            "parent_category" to "Nhóm danh mục",
            "select_parent_category" to "Chọn nhóm danh mục",
            "select_category" to "Chọn danh mục",
            "ready_to_create_category" to "Sẵn sàng tạo danh mục",
            "select_icon" to "Chọn icon",
            "no_categories" to "Không có danh mục",
            "no_categories_found" to "Không tìm thấy danh mục",
            "try_different_keywords" to "Thử từ khóa khác",
        ),
        "en" to mapOf(
            // TransactionScreen specific
            "transaction_screen_title" to "Income - Expense",
            "filter_by_time" to "Filter by time",
            "today" to "Today",
            "yesterday" to "Yesterday",
            "this_week" to "This week",
            "this_month" to "This month",
            "last_month" to "Last month",
            "this_year" to "This year",
            "all" to "All",
            "apply_filter" to "Apply filter",
            "filter" to "Filter",
            "filter_options" to "Filter options",
            "close" to "Close",
            "spending" to "Spending",
            "income" to "Income",
            "total" to "Total",
            "wallet" to "Wallet",
            "unknown_category" to "Unknown category",
            "confirm_delete_transaction" to "Are you sure you want to delete this transaction?",
            "go_back" to "Go back",
            "calendar" to "Calendar",
            "transaction_book" to "Transaction Book",
            "add_transaction" to "Add transaction",
            "financial_overview" to "Financial Overview",
            "month" to "Month",
            "total_income" to "Total income",
            "total_expense" to "Total expense",
            "difference" to "Difference",
            "monthly_income" to "Monthly income",
            "monthly_expense" to "Monthly expense",
            "transaction_count" to "Transaction count",
            "no_note" to "No note",
            "edit" to "Edit",
            "no_transactions" to "No transactions",
            "no_transactions_description" to "Start by adding your first transaction",
            "delete_transaction" to "Delete transaction",
            "delete_confirmation" to "Are you sure you want to delete the transaction",
            "confirm_delete" to "Confirm delete",
            // ALL KEYS FOR RECURRING EXPENSE FEATURE - ENGLISH VERSION
            "recurring_expenses" to "Recurring Expenses",
            "add_recurring_expense" to "Add Recurring Expense",
            "edit_recurring_expense" to "Edit Recurring Expense",
            "add_recurring_expense_button" to "Add Expense",
            "total_expenses" to "Total Expenses",
            "active_lower" to "active",
            "monthly_expenses" to "Monthly expenses:",
            "expense_info" to "Expense Information",
            "title" to "Title",
            "title_placeholder" to "e.g., Rent, Internet...",
            "amount" to "Amount",
            "category" to "Category",
            "no_categories" to "No categories available",
            "frequency" to "Frequency",
            "wallet" to "Wallet",
            "main_wallet" to "Main Wallet",
            "main_wallet_placeholder" to "Main wallet",
            "start_date" to "Start Date",
            "end_date_optional" to "End Date (Optional)",
            "select_date" to "Select Date",
            "no_end_date" to "No End Date",
            "notes" to "Notes",
            "menu" to "Menu",
            "edit" to "Edit",
            "pause" to "Pause",
            "activate" to "Activate",
            "delete" to "Delete",
            "next" to "Next",
            "generated" to "Generated",
            "times" to "times",
            "no_recurring_expenses" to "No Recurring Expenses",
            "no_recurring_expenses_yet" to "No recurring expenses yet",
            "add_recurring_expense_to_manage" to "Add recurring expenses to manage automatic spending",
            "delete_recurring_expense" to "Delete Recurring Expense",
            "confirm_delete_recurring_expense" to "Are you sure you want to delete",
            "warning" to "Warning",
            "cancel" to "Cancel",
            "action_cannot_be_undone" to "This action cannot be undone.",
            "confirm" to "Are you sure",
            "daily" to "Daily",
            "weekly" to "Weekly",
            "monthly" to "Monthly",
            "quarterly" to "Quarterly",
            "annually" to "Annually",  // or "yearly" to "Yearly"
            "currency_vnd" to "VND",
            "add_note_placeholder" to "Add note...",
            "update" to "Update",
            "back" to "Back",

            // Add Category Screen
            "create_category" to "Create Category",
            "category_information" to "Category Information",
            "click_to_change_icon" to "Click to change icon",
            "category_name" to "Category Name",
            "category_name_example" to "Example: Food, Shopping...",
            "parent_category" to "Parent Category",
            "select_parent_category" to "Select Parent Category",
            "select_category" to "Select Category",
            "ready_to_create_category" to "Ready to create category",
            "select_icon" to "Select Icon",
            "no_categories" to "No categories",
            "no_categories_found" to "No categories found",
            "try_different_keywords" to "Try different keywords",// Add/Edit Recurring Expense Screen (English)
            "edit_recurring_expense" to "Edit Recurring Expense",
            "add_recurring_expense_button" to "Add Expense",
            "expense_info" to "Expense Information",
            "title" to "Title",
            "title_placeholder" to "e.g., Rent, Internet...",
            "amount" to "Amount",
            "category" to "Category",
            "no_categories" to "No categories available",
            "frequency" to "Frequency",
            "wallet" to "Wallet",
            "main_wallet" to "Main Wallet",
            "main_wallet_placeholder" to "Main wallet",
            "start_date" to "Start Date",
            "end_date_optional" to "End Date (Optional)",
            "select_date" to "Select Date",
            "no_end_date" to "No End Date",
            "notes" to "Notes",

// Frequency (English)
            "daily" to "Daily",
            "weekly" to "Weekly",
            "monthly" to "Monthly",
            "quarterly" to "Quarterly",
            "yearly" to "Yearly",

// Reusable keys from other screens (English)
            "back" to "Back",
            "currency_vnd" to "VND",
            "add_note_placeholder" to "Add note...",
            "update" to "Update",
            // Help Screen - English
            "help" to "Help",
            "faq" to "Frequently Asked Questions",
            "contact_support" to "Contact Support",
            "usage_tips" to "Usage Tips",
            "app_info" to "App Information",

// FAQ Questions
            "faq_how_to_add_transaction" to "How to add a transaction?",
            "faq_how_to_add_transaction_answer" to "Go to the Home screen, tap the '+' button at the bottom, select 'Add Transaction', fill in the information and tap 'Save'.",
            "faq_how_to_add_wallet" to "How to add a new wallet?",
            "faq_how_to_add_wallet_answer" to "Go to the Wallets screen, tap the '+' button in the bottom right corner, enter wallet name and initial balance.",
            "faq_how_to_view_stats" to "How to view statistics?",
            "faq_how_to_view_stats_answer" to "Go to the Statistics screen from the bottom navigation bar to view charts and spending analysis.",
            "faq_how_to_logout" to "How to logout?",
            "faq_how_to_logout_answer" to "Go to the Settings screen, scroll down and select 'Logout'.",

// Contact Support
            "support_email" to "Support Email",
            "response_within_24h" to "Response within 24 hours",
            "website" to "Website",
            "detailed_guides" to "Detailed guides",
            "working_hours" to "Working Hours",
            "monday_to_friday" to "Monday - Friday",
            "working_hours_time" to "8:00 - 17:00",

// Usage Tips
            "tip_categorize_expenses" to "Categorize expenses into correct categories for accurate statistics",
            "tip_set_monthly_budget" to "Set monthly budget to control spending",
            "tip_use_recurring_expenses" to "Use recurring expenses feature for fixed expenses",
            "tip_view_weekly_stats" to "View weekly statistics to adjust spending appropriately",

// App Info
            "version" to "Version",
            "release_date" to "Release Date",
            "release_date_value" to "December, 2025",
            "developer" to "Developer",
            "developer_value" to "Finance App Team",

// Common
            "question" to "Question",
            "expand" to "Expand",
            "collapse" to "Collapse",

            // Basic app and navigation
            "language_settings" to "Language Settings",
            "choose_language" to "Choose Language",
            "current_language" to "Current Language",
            "language_saved" to "Language saved",
            "language_reset" to "Language reset",
            "save" to "Save",
            "reset" to "Reset",
            "language" to "Language",
            "app_title" to "Expense Manager",
            "cancel" to "Cancel",
            "back" to "Back",
            "next" to "Next",
            "loading" to "Loading",
            "error" to "Error",
            "success" to "Success",
            "warning" to "Warning",
            "info" to "Info",
            "add" to "Add",
            "edit" to "Edit",
            "delete" to "Delete",
            "confirm" to "Confirm",
            "current_balance" to "Current balance",
            "balance" to "Balance",
            "current_balance" to "Current Balance",
            "total_balance" to "Total Balance",
            "balance_overview" to "Balance Overview",
            "available_balance" to "Available Balance",
            "remaining_balance" to "Remaining Balance",
            "calendar" to "Calendar",
            "difference" to "Difference",
            "transaction_list" to "Transaction List",
            "select_other_day" to "Select another day to view transactions",
            "previous_month" to "Previous Month",
            "next_month" to "Next Month",
            "extensions" to "Extensions",
            "extra_tools_like_ai_calendar_scan" to "Extra tools like Category, Budget, Any Spend",

            // SettingsScreen specific
            "settings" to "Settings",
            "account" to "Account",
            "personal_info" to "Personal Information",
            "manage_account_info" to "Manage Account Information",
            "application_settings" to "Application Settings",
            "notifications" to "Notifications",
            "notifications_on" to "On",
            "notifications_off" to "Off",
            "ai_calendar_scan" to "AI, Calendar, Invoice Scan",
            "support" to "Support",
            "help" to "Help",
            "frequently_asked_questions" to "Frequently Asked Questions",
            "about_app" to "About App",
            "version" to "Version",
            "logout" to "Logout",
            "logout_account" to "Logout from Account",
            "actions" to "Actions",
            "information" to "Information",
            "language_change_info" to "Changing language will apply to the entire application",
            "close" to "Close",
            "confirm_logout" to "Are you sure you want to logout from your account?",
            "finance_app" to "Finance App",
            "personal_finance_app" to "Personal Finance Management App",
            "release_date" to "Release Date",
            "footer_copyright" to "Finance App © 2025",

            // Budget Screen
            "budgets" to "Budgets",
            "add_budget" to "Add Budget",
            "total_budget" to "Total Budget",
            "active" to "active",
            "spent" to "Spent",
            "unknown_category" to "Unknown Category",
            "menu" to "Menu",
            "edit" to "Edit",
            "pause" to "Pause",
            "activate" to "Activate",
            "delete" to "Delete",
            "remaining" to "Remaining",
            "no_budgets" to "No budgets",
            "no_budgets_yet" to "No budgets yet",
            "add_budget_to_manage_spending" to "Add budget to manage spending",
            "this_budget" to "this budget",
            "warning" to "Warning",
            "delete_budget" to "Delete Budget",
            "confirm_delete_budget" to "Are you sure you want to delete",
            "action_cannot_be_undone" to "This action cannot be undone",
            "confirm" to "Are you sure you want to",

// Budget periods
            "week" to "week",
            "month" to "month",
            "quarter" to "quarter",
            "year" to "year",
            // HomeScreen specific
            "home" to "Home",
            "greeting" to "Hello",
            "user" to "User",
            "income" to "Income",
            "expense" to "Expense",
            "this_month" to "This month",
            "recent_transactions" to "Recent transactions",
            "view_all" to "View all",
            "no_recent_transactions" to "No recent transactions",
            "create_transaction" to "Create transaction",
            "spending_chart_title" to "Spending last 7 days",
            "monthly_spent" to "This month",
            "budget_title" to "Monthly budget",
            "manage_budget" to "Manage budget",
            "tracking_budget" to "Tracking",
            "setup_budget" to "Set up budget",
            "setup_budget_description" to "Set up budget to control spending",
            "view_details" to "View details",
            "setup_budget_button" to "Set up budget",
            "spent" to "Spent",
            "budget" to "Budget",
            "remaining" to "Remaining",
            "over_budget" to "Over budget",
            "spending_7_days" to "Spending last 7 days",
            "no_chart_data" to "No chart data",
            "income_card_title" to "Income",
            "expense_card_title" to "Expense",
            "transaction" to "Transaction",
            "today" to "Today",
            "yesterday" to "Yesterday",
            "amount" to "Amount",
            "description" to "Description",
            "calendar" to "Calendar",
            "greeting" to "Hello",
            "user" to "User",
            "monthly_spending_title" to "Your monthly spending",
            "view_details" to "View details",
            "spent_this_month" to "Amount spent this month",
            "classification_by_type" to "Spending by category",
            "recent_transactions" to "Recent transactions",
            "view_all" to "View all",
            "income" to "Income",
            "expense" to "Expense",
            "no_recent_transactions" to "No recent transactions",
            "create_transaction" to "Create transaction",
            "overview" to "Overview",
            "this_month" to "This month",
            "spending_limit" to "Spending limit",
            "create_or_select_fund_for_limit" to "Create or select savings fund",
            "limit_description" to "to help calculate spending limit",
            "select_or_create_fund" to "Select / Create fund",
            "no_chart_data" to "No chart data",
            "spending_by_category" to "Spending by category",
            "daily_spending" to "Daily spending",
            "savings_fund" to "Savings fund",
            "needs" to "Necessary",
            "training" to "Training",
            "entertainment" to "Entertainment",
            "savings" to "Savings",
            "self_care" to "Self-care",
            "free_spending" to "Free spending",
            "limit" to "Limit",
            "spent" to "Spent",
            "see_more" to "See more",
            "monthly_spending_total" to "Monthly spending total",
            "transactions" to "Transactions",
            "profile" to "Profile",
            // =============================================

            // Days of week (short)
            "monday_short" to "Mon",
            "tuesday_short" to "Tue",
            "wednesday_short" to "Wed",
            "thursday_short" to "Thu",
            "friday_short" to "Fri",
            "saturday_short" to "Sat",
            "sunday_short" to "Sun",

            // Days of week (full)
            "monday" to "Monday",
            "tuesday" to "Tuesday",
            "wednesday" to "Wednesday",
            "thursday" to "Thursday",
            "friday" to "Friday",
            "saturday" to "Saturday",
            "sunday" to "Sunday",

            // Months
            "january" to "January",
            "february" to "February",
            "march" to "March",
            "april" to "April",
            "may" to "May",
            "june" to "June",
            "july" to "July",
            "august" to "August",
            "september" to "September",
            "october" to "October",
            "november" to "November",
            "december" to "December",

            // Help & Support
            "help_support" to "Help & Support",
            "faq" to "Frequently Asked Questions",
            "faq_add_transaction" to "How to add a transaction?",
            "faq_add_transaction_answer" to "Go to Home → tap the blue \"+\" button at the bottom right",
            "faq_view_statistics" to "How to view statistics?",
            "faq_view_statistics_answer" to "Go to Statistics → select time range and data type to view",
            "faq_logout" to "How to logout?",
            "faq_logout_answer" to "Go to Settings → scroll down → select \"Sign Out\"",
            "faq_change_theme" to "How to change theme?",
            "faq_change_theme_answer" to "Go to Settings → toggle \"Theme Mode\"",
            "contact_support" to "Contact Support",
            "contact_description" to "If you need additional support or encounter technical issues, please contact:",
            "email" to "Email",
            "website" to "Website",
            "working_hours" to "Working Hours",
            "response_time" to "Response within 24h",
            "detailed_guide" to "Detailed guides",
            "weekdays" to "Monday - Friday",
            "working_time" to "8:00 - 17:00",
            "usage_tips" to "Usage Tips",
            "tip_categories" to "Use categories to clearly classify expenses",
            "tip_savings" to "Set savings goals to track progress",
            "tip_statistics" to "View monthly statistics to adjust spending",
            "tip_reminders" to "Use reminder feature for recurring bills",

            // Notification settings
            "notification_settings" to "Notification Settings",
            "customize_notifications" to "Customize how you receive notifications",
            "notification_types" to "Notification Types",
            "push_notifications" to "Push Notifications",
            "email_notifications" to "Email Notifications",
            "sms_notifications" to "SMS Notifications",
            "financial_alerts" to "Financial Alerts",
            "low_balance_alert" to "Low Balance Alert",
            "large_transaction_alert" to "Large Transaction Alert",
            "monthly_report" to "Monthly Report",
            "restore" to "Restore",
            "save_settings" to "Save Settings",
            "settings_restored" to "Settings restored",
            "settings_saved" to "Notification settings saved",

            // Main navigation
            "home" to "Home",
            "statistics" to "Statistics",
            "transactions" to "Transactions",
            "categories" to "Categories",
            "reports" to "Reports",
            "account" to "Account",

            // HomeScreen (phần cũ - giữ lại cho tương thích)
            "total_balance" to "Total balance",
            "need_attention" to "Need attention",
            "stable" to "Stable",
            "status" to "Status",
            "financial_trend" to "Financial trend",
            "month" to "Month",
            "spending" to "Spending",
            "total" to "Total",
            "line_chart" to "Line chart",
            "column_chart" to "Column chart",
            "pie_chart" to "Pie chart",
            "no_data" to "No data to display",
            "no_spending_data" to "No spending data to display",
            "no_transactions" to "No transactions",

            // TransactionScreen
            "transaction_book" to "Transaction Book",
            "transactions_count" to "transactions",
            "financial_overview" to "Financial Overview",
            "monthly_income" to "Monthly Income",
            "monthly_expense" to "Monthly Expense",
            "transaction_count" to "Transaction Count",
            "transaction_history" to "Transaction History",
            "no_note" to "No note",
            "delete_transaction" to "Delete Transaction",
            "delete_confirmation" to "Are you sure you want to delete the transaction",
            "confirm_delete" to "Confirm Delete",
            "no_transactions_description" to "Start by adding your first transaction",

            // AddTransactionScreen
            "record_transaction" to "Record Transaction",
            "manual_input" to "Manual Input",
            "image_input" to "Image Input",
            "select_category" to "Select Category",
            "transaction_date" to "Transaction Date",
            "today" to "Today",
            "repeat_frequency" to "Repeat Frequency",
            "no_repeat" to "No Repeat",
            "daily" to "Daily",
            "weekly" to "Weekly",
            "monthly" to "Monthly",
            "note" to "Note",
            "enter_transaction_description" to "Enter transaction description",
            "update_transaction" to "Update Transaction",
            "add_income_transaction" to "Add Income Transaction",
            "add_expense_transaction" to "Add Expense Transaction",
            "delete_transaction_dialog" to "Delete Transaction",
            "delete_transaction_description" to "Are you sure you want to delete this transaction?",
            "delete_action" to "Delete",

            // Categories
            "food_drink" to "Food & Drink",
            "shopping" to "Shopping",
            "family" to "Family",
            "other" to "Other",

            // Account info
            "account_info" to "Account Information",
            "update_personal_info" to "Update Personal Information",
            "full_name" to "Full Name",
            "email" to "Email",
            "phone_number" to "Phone Number",
            "read_only" to "Read Only",
            "update_success" to "Update Successful",
            "saving" to "Saving...",
            "save_changes" to "Save Changes",
            "system_info" to "System Information",
            "user_id" to "User ID",
            "not_available" to "Not Available",
            "provider" to "Provider",
            "email_verification" to "Email Verification",
            "verified" to "Verified",
            "not_verified" to "Not Verified",
            "created_at" to "Created At",
            "last_login" to "Last Login",
            "unknown" to "Unknown",
            "email_password" to "Email/Password",
            "google" to "Google",
            "facebook" to "Facebook",
            "phone" to "Phone",

            // Common transaction fields
            "amount" to "Amount",
            "description" to "Description",
            "date" to "Date",
            "category" to "Category",
            "add_expense" to "Add Expense",
            "expense_list" to "Expense List",
            "add_transaction" to "Add transaction",
            "total_income" to "Total income",
            "total_expense" to "Total expense",
            "this_week" to "This week",
            "this_year" to "This year",
            "trend_analysis" to "Trend analysis",
            "category_analysis" to "Category analysis",

            // Settings and account
            "manage_personal_info" to "Manage personal information",
            "enable_disable_notifications" to "Enable / disable notifications",
            "theme_mode" to "Theme mode",
            "sign_out" to "Sign out",
            "logout_account" to "Log out of your account",

            // Đảm bảo các key này đã có
            "statistics" to "Statistics",
            "time_range" to "Time Range",
            "time_range_weekly" to "Weekly",
            "time_range_monthly" to "Monthly",
            "time_range_yearly" to "Yearly",
            "data_type" to "Data Type",
            "data_type_income" to "Income",
            "data_type_expense" to "Expense",
            "data_type_difference" to "Difference",
            "total" to "Total",
            "same_period_as" to "Same period as",
            "info" to "Info",
            "total_income" to "Total Income",
            "total_expense" to "Total Expense",
            "difference" to "Difference",
            "no_data" to "No data",
            "no_transactions_time_period" to "You have no transactions in this time period",
            "compare" to "Compare",
            "with" to "with",
            "this_week" to "This week",
            "this_month" to "This month",
            "this_year" to "This year",
            "last_week" to "last week",
            "last_month" to "last month",
            "last_year" to "last year",
            "current_week" to "Current Week",
            "current_month" to "Current Month",
            "current_year" to "Current Year",
            "previous_week" to "Previous Week",
            "previous_month" to "Previous Month",
            "previous_year" to "Previous Year",
            "category_analysis" to "Category Analysis",
            "category" to "Category",
            "amount" to "Amount",
            "unknown_category" to "Unknown Category",

            // Category Management
            "create_category" to "Create Category",
            "click_to_change_icon" to "Tap to change icon",
            "category_name" to "Category Name",
            "category_name_example" to "Example: Food, Shopping...",
            "parent_category" to "Parent Category",
            "select_parent_category" to "Select Parent Category",
            "select_category" to "Select Category",
            "icon" to "Icon",
            "ready_to_create_category" to "Ready to create category",
            "select_icon" to "Select Icon",
            "select_group_for_new_category" to "Select group for new category",
            "search_categories" to "Search categories...",
            "found" to "Found",
            "categories" to "categories",
            "no_categories_found" to "No categories found",
            "try_different_keywords" to "Try different keywords",
            "main_category" to "Main Category",
            "sub_category" to "Sub Category",
            "category_management" to "Category Management",
            "add_new_category" to "Add New Category",
            "has" to "Has",
            "add_sub_category" to "Add Sub Category",
            "no_sub_categories" to "No sub categories",
            "sub_categories" to "sub categories",
            // Extensions Screen
            "extensions" to "Extensions",
            "expense_categories" to "Expense Categories",
            "customize_spending_categories" to "Customize spending categories",
            "budgets" to "Budgets",
            "set_and_track_monthly_budget" to "Set and track monthly budget",
            "recurring_expenses" to "Recurring Expenses",
            "manage_automatic_monthly_expenses" to "Manage automatic monthly expenses",
            "savings_goals" to "Savings Goals",
            "track_and_achieve_savings_targets" to "Track and achieve savings targets",
            "advanced_features" to "Advanced Features",
            "receipt_scan" to "Receipt Scan",
            "scan_receipts_auto_input_expenses" to "Scan receipts auto-input expenses",
            "ai_analysis" to "AI Analysis",
            "ai_powered_spending_analysis" to "AI-powered spending analysis",
            "coming_soon" to "Coming Soon",
            "unavailable" to "Unavailable"
        )
    )

    // Danh sách ngôn ngữ hỗ trợ
    private val availableLanguages = listOf(
        Language("vi", "Tiếng Việt"),
        Language("en", "English")
    )

    // Get available languages
    fun getAvailableLanguages(): List<Language> {
        return availableLanguages
    }

    // Change language - updated to work with Language object
    fun changeLanguage(languageCode: String) {
        val language = availableLanguages.find { it.code == languageCode }
        if (language != null) {
            _currentLanguage.value = language
            _languageCode.value = languageCode
        }
    }

    // New method to set language directly with Language object
    fun setLanguage(language: Language) {
        _currentLanguage.value = language
        _languageCode.value = language.code
    }

    // Get translation for a key
    fun getTranslation(key: String, fallbackLanguage: String = "en"): String {
        val currentLangCode = _languageCode.value
        return translations[currentLangCode]?.get(key) ?:
        translations[fallbackLanguage]?.get(key) ?: key
    }

    // Get current language name
    fun getCurrentLanguageName(): String {
        return _currentLanguage.value.name
    }

    // Get language from code
    fun getLanguageFromCode(code: String): Language {
        return availableLanguages.find { it.code == code } ?: availableLanguages[0]
    }

    // Set language from code (for initialization)
    fun setLanguageFromCode(code: String) {
        val language = getLanguageFromCode(code)
        _currentLanguage.value = language
        _languageCode.value = code
    }

    // Get current language code
    fun getCurrentLanguageCode(): String {
        return _languageCode.value
    }

    // Initialize with saved language
    fun initializeWithSavedLanguage(savedCode: String) {
        setLanguageFromCode(savedCode)
    }
}