package com.example.financeapp.data.models

import com.example.financeapp.viewmodel.transaction.Category

data class Transaction(
    val id: String = "",
    val date: String = "",
    val dayOfWeek: String = "",
    val category: String = "",
    val categoryId: String = "",
    val amount: Double = 0.0,
    val isIncome: Boolean = false,
    val group: String = "",
    val wallet: String = "",
    val description: String = "",
    val categoryIcon: String? = null,
    val categoryColor: String? = null,
    val createdAt: Long = System.currentTimeMillis(),
    val title: String = "",
    val isAutoGenerated: Boolean = false,
    val recurringSourceId: String = ""
) {
    fun toMap(): Map<String, Any> {
        return mapOf(
            "id" to id,
            "date" to date,
            "dayOfWeek" to dayOfWeek,
            "category" to category,
            "categoryId" to categoryId,
            "amount" to amount,
            "isIncome" to isIncome,
            "group" to group,
            "wallet" to wallet,
            "description" to description,
            "categoryIcon" to (categoryIcon ?: ""),
            "categoryColor" to (categoryColor ?: ""),
            "createdAt" to createdAt,
            "isAutoGenerated" to isAutoGenerated,
            "recurringSourceId" to recurringSourceId
        )
    }

    companion object {
        fun fromMap(map: Map<String, Any>): Transaction {
            return Transaction(
                id = map["id"] as? String ?: "",
                date = map["date"] as? String ?: "",
                dayOfWeek = map["dayOfWeek"] as? String ?: "",
                category = map["category"] as? String ?: "",
                categoryId = map["categoryId"] as? String ?: "",
                amount = (map["amount"] as? Double) ?: 0.0,
                isIncome = map["isIncome"] as? Boolean ?: false,
                group = map["group"] as? String ?: "",
                wallet = map["wallet"] as? String ?: "",
                description = map["description"] as? String ?: "",
                categoryIcon = map["categoryIcon"] as? String,
                categoryColor = map["categoryColor"] as? String,
                createdAt = (map["createdAt"] as? Long) ?: System.currentTimeMillis(),
                isAutoGenerated = map["isAutoGenerated"] as? Boolean ?: false,
                recurringSourceId = map["recurringSourceId"] as? String ?: ""
            )
        }
    }

    fun copyWithCategoryInfo(category: Category?): Transaction {
        return this.copy(
            category = category?.name ?: this.category,
            categoryId = category?.id ?: this.categoryId,
            categoryIcon = category?.icon ?: this.categoryIcon,
            categoryColor = category?.color ?: this.categoryColor
        )
    }
}